# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.dev3+gfdc9876.d20230507'
__version_tuple__ = version_tuple = (0, 2, 'dev3', 'gfdc9876.d20230507')
